### ISSUE TITLE
"Orphaned instance" when rerendering DOM

### ISSUE THREAD

**Issue by thSoft** [witheve/Eve#834] opened 2017-05-30 16:48 UTC
# Eve version

0.3-preview4

# Steps to reproduce
```
git clone git@github.com:thSoft/eve-starter.git
cd eve-starter
npm install
open http://localhost:8000/app/eveRoot/treemap.eve
```
Click on the plus sign on the right side of `Qux` or `Bee`

# Expected result

The clicked node will be maximized

# Actual result

Exception in developer console:

```
runtime.ts:3520 Uncaught Error: Orphaned instance 'tag|html/instance|element|children|children|class|title|node|children|eve-auto-index|2|sort|1|tag|node|title|Bee|children|eve-auto-index|1|sort|0|tag|node|title|Qux|sort|0|tag|node|title|Bar|tag|ui/span|tag|title-view|tag|html/element|tagname|summary|class|node|node|children|eve-auto-index|2|sort|1|tag|node|title|Bee|children|eve-auto-index|1|sort|0|tag|node|title|Qux|sort|0|tag|node|title|Bar|sort|0|tag|html/element|tag|node-view|tagname|details|tagname|details'
    at HTMLWatcher.createRoot (html.ts:32)
    at eval (dom.ts:210)
    at Transaction.Exporter.handle [as exportHandler] (watcher.ts:118)
    at Transaction.exec (runtime.ts:3517)
    at Program.input (dsl2.ts:1793)
    at Program.inputEAVs (dsl2.ts:1821)
    at HTMLWatcher.DOMWatcher._sendEvent (dom.ts:25)
    at eval (html.ts:125)
HTMLWatcher.createRoot	@	html.ts:32
(anonymous)	@	dom.ts:210
Exporter.handle	@	watcher.ts:118
Transaction.exec	@	runtime.ts:3517
Program.input	@	dsl2.ts:1793
Program.inputEAVs	@	dsl2.ts:1821
DOMWatcher._sendEvent	@	dom.ts:25
(anonymous)	@	html.ts:125
```

**Comment by joshuafcole** [comment] 2017-05-31 00:24
Hey @thSoft,

It wouldn't surprise me if you've found an issue in the new experimental renderer. Can you please post your Eve program (or a repro case) on [GitHub Gists](https://gist.github.com/) and link it here so that I can diagnose the problem?

**Comment by thSoft** [comment] 2017-05-31 05:46
Sure, here it is: https://gist.github.com/thSoft/7cbf2dc245e4b72eabfb20a1233d83f6 <https://gist.github.com/thSoft/7cbf2dc245e4b72eabfb20a1233d83f6>
(original, non-Gist location: https://github.com/thSoft/eve-starter/blob/master/programs/treemap.eve)

**Comment by joshuafcole** [comment] 2017-06-01 22:47
@thSoft, I am able to reproduce your issue and am diagnosing it now. Thanks for getting back to me so quickly!

**Comment by joshuafcole** [comment] 2017-06-02 03:09
Hey @thSoft,

Quick update on the situation. I've isolated the source of the error (the renderer is being told that the newly-maximized `#node-view` is both being made into an `#html/root` (correct!) and being deleted (very, very incorrect) at the same time. This is a logical paradox that the new renderer guards against, which is how we were able to find out about it. This suggests the root of the problem is actually in an interesting runtime or watcher interface bug.

I'm digging into this now, but the size of the example makes this slow going. I've tried to isolate the problem by starting from scratch and successively building up to your example without much luck. I can't reliably reproduce the crash until the repro is about as large as the original. My suspicion is that creating and then re-parenting elements is at the root of this, but I haven't determined why that would be an issue yet. I'm going to keep plugging away at that, but if you happen to find a smaller program that exhibits the same issue, *please* send it my way.

In the meantime, if you're interested, I tried an implementation that doesn't do reparenting, which seems to work fine. If don't want to have to wait around for me to get this fixed, you can try rewriting your version along these lines. I hadn't seen that you gave a GH link with the treemap CSS at the time, so I added a little of my own.

https://gist.github.com/anonymous/c5725400e5f1dceefa188a418bd43285

**Comment by thSoft** [comment] 2017-06-02 18:26
Wow, thanks for the committed investigation! I understand that the example is far from being minimal, I'm trying to reduce it.

**Comment by thSoft** [comment] 2017-06-02 18:53
I localized the problem: if I change the `details` and `summary` tags to simple `#ui/div`-s, the problem goes away. So maybe it has to do something with the renderer keeping some state of the `details` element?

**Comment by joshuafcole** [comment] 2017-06-02 22:43
Great news! It was a bit of an adventure to get to the root cause, but it turns out you caught a potentially very serious bug in the watcher interface itself! Watcher's should be a lot more robust for users going forward thanks to your consistent repro case. :+1: We'd like to send you a few stickers to say thank you. Shoot myself or @cmontella an email /(corey|josh)/ at kodowa.com if you're interested and we'll work out where to send them.

We'll get this patch merged into master today and test it over the weekend to publish next week.

**Closed** 2017-06-02 23:41 UTC
Labels: bug
