### ISSUE TITLE
"Unable to get packages from source" messages repeatedly. Eve never loads

### ISSUE THREAD

**Issue by damienstanton** [witheve/Eve#234] opened 2015-08-20 16:37 UTC
Eve appears to compile partially but is unable to continue past the waiting room. `multirust` and `tsc` are good to go, and I am on OS X 10.10.5.

Firing up the `run.sh` script:

```sh
* Checking dependencies...
~/Eve ~/Eve
* Compiling Editor...
~/Eve
* Opening /Users/damien/Eve/ui/waiting-room.html
~/Eve ~/Eve
* Updating rust if necessary...
multirust: using existing install for 'nightly-2015-08-10'
multirust: override toolchain for '/Users/damien/Eve/runtime' set to 'nightly-2015-08-10'
* Compiling server... (This takes a while)
 Downloading pkg-config v0.3.5
Unable to get packages from source

To learn more, run the command again with --verbose.
~/Eve
```

If I run again:

```sh
* Checking dependencies...
~/Eve ~/Eve
* Compiling Editor...
~/Eve
* Opening /Users/damien/Eve/ui/waiting-room.html
~/Eve ~/Eve
* Updating rust if necessary...
multirust: using existing install for 'nightly-2015-08-10'
multirust: override toolchain for '/Users/damien/Eve/runtime' set to 'nightly-2015-08-10'
* Compiling server... (This takes a while)
 Downloading winapi-build v0.1.0
Unable to get packages from source
To learn more, run the command again with --verbose.
~/Eve
```

And again:

```sh
* Checking dependencies...
~/Eve ~/Eve
* Compiling Editor...
~/Eve
* Opening /Users/damien/Eve/ui/waiting-room.html
~/Eve ~/Eve
* Updating rust if necessary...
multirust: using existing install for 'nightly-2015-08-10'
multirust: override toolchain for '/Users/damien/Eve/runtime' set to 'nightly-2015-08-10'
* Compiling server... (This takes a while)
 Downloading traitobject v0.0.1
Unable to get packages from source
To learn more, run the command again with --verbose.
~/Eve
```

This occurs with several different libraries, and bounces between them; `rand` and `traitobject` appeared a couple times more than others.

Adding the `--verbose` flag doesn't actually increase the verbosity, or seem to do anything else.

What could be causing this?

**Comment by joshuafcole** [comment] 2015-08-20 18:14
Duplicate of: #227

I'll set the run script up to pass the verbose flag into cargo. This is a cargo related issue yet again,  and I've been unable to reproduce it. It may be due to an idiosyncrasy of your network or due to instability in cargo's repository. See if you can follow the tips here rust-lang/cargo#1258 to get things resolved.

**Closed** 2015-08-24 22:04 UTC
Labels: duplicate
