### ISSUE TITLE
Inline CSS not working when running eve *.eve command

### ISSUE THREAD

**Issue by cakenggt** [witheve/Eve#718] opened 2017-01-02 03:00 UTC
Using the npm witheve package to run a file does not load the css from the file.

Use the following gist
https://gist.githubusercontent.com/anonymous/710df37a0e9706193ee9198519595d5e

Once you save it into a file, lets say `test.eve`, run the command `eve test.eve` on it to load it in a browser.

View it with the browser, and you will see that the todo items do not get line-through'd, even though their class does change to 'done' when clicked (viewed with the browser inspector).

**Comment by joshuafcole** [comment] 2017-01-05 21:58
This is a dupe of #704. Let's track it there instead.

**Closed by joshuafcole** 2017-01-05 21:58 UTC
