### ISSUE TITLE
changes to documents not loaded

### ISSUE THREAD

**Issue by davidak** [witheve/Eve#586] opened 2016-11-20 23:58 UTC
i used `test.eve` to test out some things, open another example and go back but my changes are gone :(

they are actually saved to the filesystem but not loaded again.

very frustrating!

then i created a new document. it's name is `untitled.eve` and i can't change the name in the IDE. also when i add content and reload the browser or came back from another example, it is empty again. but again it is saved, but not loaded again!

---

Eve git master at 59f6ec986453087e4ea0821e9a170c33cfc98e75
node v6.9.1
npm 3.10.8
elementary OS 0.4 Loki (Ubuntu 16.04 based)

**Comment by cmontella** [comment] 2016-11-22 21:20
David,

Sorry you're frustrated, that's definitely not the experience we want to provide. Unfortunately, saving/loading is a rough edge right now, because there are many ways it can go wrong... you found one of them.

I can reproduce your issue like so:

1 - start Eve
2 - connect to Eve
3 - create a new untitled.eve file in the editor
4 - edit the file
5 - confirm changes in editor are reflected on disk
6 - navigate to another example, then back to untitled.eve. The changes are not there.
7 - refresh the browser, the changes are loaded

Are those the steps you took?

> then i created a new document. it's name is untitled.eve and i can't change the name in the IDE.

Yes, this isn't currently supported. I'll make an issue to track this: https://github.com/witheve/Eve/issues/595

**Comment by ibdknox** [comment] 2016-11-22 21:30
@joshuafcole so I think the issue is that for a fresh load we get information from the server, when you use the ToC to navigate we're loading from local storage.

**Comment by joshuafcole** [comment] 2016-11-22 22:01
A hard refresh is currently required to update the local cache. The current
system is unnecessarily married to the client-only filestore used by
play.witheve.com, making other workflows very awkward. That just needs to
be fixed.

However, I'm not sure that's really the issue here? A hard refresh should
still pull the latest copy of the file, as Corey stated.

**Comment by cmontella** [comment] 2016-11-22 22:05
The problem is that it's unexpected. The user just edited the file in the browser, went away and came back, and his changes are gone. The reaction there is panic and frustration, at the thought of just losing all of the code you just typed.

**Comment by ibdknox** [comment] 2016-11-22 22:41
Not just unexpected it trivially leads to lost work. Make some changes, navigate, come back, make some more changes. You just lost your first set.

**Comment by davidak** [comment] 2016-11-23 00:40
@cmontella 

>Are those the steps you took?

I'm really sure when i reported this issue a simple reload dosn't help. I had updated to a9192256aadc3bffe2cff2969d058e369d784862 and now that works.

As @ibdknox stated, i also have overwritten my first changes. It was just some simple tests but i stopped there playing around.

This is actually a very interesting project and i like to play around with it. I hope my bugreports help to improve the user expereance. Keep up the good work!

**Comment by cmontella** [comment] 2016-11-23 01:03
> I hope my bugreports help to improve the user expereance. Keep up the good work!

@davidak absolutely, we know where the problem is here, so thanks for the help :)

**Comment by joshuafcole** [comment] 2016-12-02 23:41
@davidak apologies for the long delay on fixing this. I hadn't understood the severity of this issue or it would have been my first priority. This sort of faux pas won't happen again. Even as a new language it's critically important that we look out for our users first and foremost.

The current release (0.2.2) doesn't make this experience as good as it needs to be, but it eliminates this case that leads to trivially lost work. Until the more robust solution is in place, It's still dangerous to edit via the editor, an external editor, and the editor again. Fixing that unfortunately necessitates a little restructuring work, but it's on the top of my todo list.

I'm going to close the issue here and track the remaining work in #635. As ever, feel free to comment with any other issues or concerns, and thanks again for your patience.

**Closed by joshuafcole** 2016-12-02 23:41 UTC
