### ISSUE TITLE
Eve Quick Start Tutorial BUG

### ISSUE THREAD

**Issue by massanchik** [witheve/Eve#499] opened 2016-10-31 17:56 UTC
On [tutorial page](http://play.witheve.com/#/examples/quickstart.eve) in the last example, where you handling form submit, form fields does not reset.

**Comment by DjebbZ** [comment] 2016-10-31 21:52
Duplicate of #486, that I opened 2 days ago. Same problem than you. Could you close this issue and follow the other ?

**Comment by massanchik** [comment] 2016-10-31 22:50
Yea, sure.

**Closed** 2016-10-31 22:50 UTC
