### ISSUE TITLE
Merge of object with multiple children gives segmentation fault

### ISSUE THREAD

**Issue by btheado** [witheve/Eve#429] opened 2016-08-17 01:21 UTC
Maybe I'm doing it wrong and my code is infinitely recursive, but even so it should be caught as an error rather than Segmentation fault as the below code gives for me.

Display a button
```
bind
  [#button children: [#icon @edit-button]]
```

"Macro" for button contents. Define it separately so it can be reused
```
  match
    icon = [#icon @edit-button]
  bind 
    // With a single div child it works fine
    //icon <- [#div children: [#div text: "edit me"]]

    // But with two children, eve crashes with Segmentation fault
    icon <- [#div children:
               [#div text: "edit"]
               [#div text: "me"]]          
```

**Comment by ibdknox** [comment] 2016-08-17 02:16
This is failing to fixpoint (in the F timestep), because it's constantly removing and adding the children. I feel like this *should* work though. We'll have to talk about it and see if there's something that makes sense.

**Comment by joshuafcole** [comment] 2016-08-18 01:25
Yeah, it's flip-flopping between insert on even ticks and remove on odd ticks, rather than insert/remove both on every tick, like I would expect. This seems likely to be a bug in our multiplicity logic, caused by

```
    icon <- [#div children:
               [#div text: "edit"]
               [#div text: "me"]]
```

devolving into two set operations:

```
--- Unpacked Objects / Mutates ---
  {
     ...
     7: SubprojectNode #{ variable<icon>, variable<object-17-15>} -> #{ } {
          ScanNode{type: mutate, operator: set, scope: event, entity: variable<icon>, attribute: children, value: variable<object-17-15>}
        }
     8: SubprojectNode #{ variable<icon>, variable<object-18-15>} -> #{ } {
          ScanNode{type: mutate, operator: set, scope: event, entity: variable<icon>, attribute: children, value: variable<object-18-15>}
        }
  }
```

or something similar. This should be valid.

**Comment by joshuafcole** [comment] 2016-08-18 01:28
Also, @btheado: we now catch the divergence error as of #422. Displaying it to the user still needs a lot of work, but we'll terminate the evaluation instead of segfaulting and drop a warning in the dev console at least.

**Comment by cmontella** [comment] 2016-10-19 00:33
fixed on ts-merge

**Closed by cmontella** 2016-10-19 00:33 UTC
Labels: bug, executor
