### ISSUE TITLE
Evaluation failed to fixpoint

### ISSUE THREAD

**Issue by wilk** [witheve/Eve#720] opened 2017-01-05 15:58 UTC
Hi guys,

first of all, thanks for what you've done until now: Eve is totally a new brand approach to web development ;)

So, I'm playing with it but it seems I'm doing something wrong when I try to increment an attribute of an existing record.
The Eve's IDE throws the following error: `Evaluation failed to fixpoint`
The problem occurs in the following block:

```eve
commit @race
  competitor.score := competitor.score + 1
```

`competitor.score` has an initial value of `0` but when that statement get executed, the error is thrown and it gets the value of `299` or `300`.
It seems the problem is related to this section: https://github.com/witheve/Eve/blob/master/src/runtime/runtime.ts#L241

What's wrong with that code? Is there another way to increment a number attribute?

The whole source code of the program is here enclosed: [race.eve.txt](https://github.com/witheve/Eve/files/687661/race.eve.txt)
Or here as a gist: https://gist.github.com/wilk/fd64a50fb55a2a23cc04171a9b42ac94

I'm using:

- Eve 0.2.3
- Chrome 55
- Mac OS X 10.11.6

Many thanks!
Wilk

**Comment by cmontella** [comment] 2017-01-05 22:09
@wilk,

Actually what you did was fine, the problem is something else. Here you can see it incrementing a random player's score when you click the list, instead of each second: http://play.witheve.com/#gist:be261d8998641074e033c9d2a4d879d0-root-87f4fab-examples-untitled.eve

To see the problem, let's take a look at the original block:

```eve
search @session
  [#time seconds] 

search @race
  randomId = floor[value: random[seed: seconds] * 10]
  competitor = [#competitor id: randomId, name, score]

commit @race
  competitor.score := competitor.score + 1
```

The thing to be aware of here is that Eve will execute a block whenever there is new data. You can see that you have a recursive relation here, because you are both searching for `competitor.score` and updating `competitor.score`. Because of this, Eve re-runs the block continually until it hits the limit (which is 300, so that's why you're seeing that value.).

You were expecting the block to run only once a second, but even though `[#time seconds]` updates once a second, `[#competitor]` updates more frequently (as fast as Eve can go) and therefore the block runs more than once a second.

To prevent this, you can add a rule that say "if the current second has already seen an update, don't update". Such a rule would look like this:

```eve
search
  [#time seconds timestamp]
  not([#updated timestamp])
    
search @race
  randomId = floor[value: random[seed: timestamp] * 10]
  competitor = [#competitor id: randomId, name, score]

commit
  [#updated timestamp]
  
commit @race
  competitor.score := competitor.score + 1
```

The critical bits are that we search for `not([#updated timestamp])`, but then commit `[#updated timestamp]`. This means that the first time through, the block executes, so `competitor.score` is incremented by 1. This would normally cause the block to execute again, but this time the `not()` prevents it from doing so.

I hope this explanation helps. Let me know if you want me to walk you through the computation step by step. I'm going to close the issue though.

**Closed by cmontella** 2017-01-05 22:09 UTC
