### ISSUE TITLE
Markup not preserved when cut-pasting within the editor

### ISSUE THREAD

**Issue by nmsmith** [witheve/Eve#582] opened 2016-11-20 00:59 UTC
When cutting (or copying) and pasting text within the editor, only the raw text is transferred. All markup is lost.

Tested on MacOS in Chrome and Safari.

**Comment by olafleur** [comment] 2016-11-20 01:54
Could you clarify you are talking about cutting and pasting from where to where?

What is the observed behavior and what would be the expected one?

**Comment by nmsmith** [comment] 2016-11-20 02:14
I'm referring to cutting (or copying) and pasting within the editor (I updated my original text). This should be replicable by trying to copy a code block.

<img width="143" alt="screen shot 2016-11-20 at 1 12 31 pm" src="https://cloud.githubusercontent.com/assets/909604/20459804/0fdf57ae-af23-11e6-8e9a-ce22812195b4.png">

**Comment by olafleur** [comment] 2016-11-20 02:26
Not sure that I understand. If I take code from within a code block and to a code block, everything is fine.
If I take code from a code block and paste it outside the code block, there is no formatting because you are not in a code block anymore.

I guess that this is the intended behavior, from what I understand.

**Comment by nmsmith** [comment] 2016-11-20 02:34
If code is copied from _within_ a code block, then sure, it is reasonable to consider it text. But when I want to move an entire code block from one location to another, or a section of a page containing multiple code blocks and/or headings, highlighting an entire region and cut/pasting it leaves you with only plain text.

**Example**
Highlighting and copying multiple items:
![image](https://cloud.githubusercontent.com/assets/909604/20459879/fa4cab1e-af25-11e6-86e5-4cf9b196b420.png)

Result of pasting:
![image](https://cloud.githubusercontent.com/assets/909604/20459881/0736896c-af26-11e6-9acb-1e050499424a.png)

**Comment by olafleur** [comment] 2016-11-20 02:35
Ok, now I understand. Thanks for the clarification !

**Comment by joshuafcole** [comment] 2016-12-06 03:04
There are a few possible solutions to this, each with their own set of work. The easiest is probably to attach the markup information to the clipboard using the clipboard API, but unfortunately IE and Edge implement only a subset of this.**

Alternatively, we can serialize the copied section to markdown and fix the writing markdown directly problem. This requires a lot more work unfortunately, particularly around the edge-cases of copying partial spans. E.g., if you copy half a bolded span, what is the correct behavior? The naive approach would be incorrect, inserting a single asterisk at the end of that segment. A fancier approach of making partials their own whole span interacts strangely with our other requirements (that spans begin and end at whole-word boundaries) which are necessary due to the parsing rules of CommonMark.

This is (obviously!) a very important issue, but it's also a tricky one to solve well. The fix for this is unfortunately probably going to be a little ways out, but I want to keep the line of communication open.

As always, if anybody has specific thoughts on how to circumvent these issues, I'm all ears!

** There's potentially a hacky solution to fake the necessary bits of clipboard state by keeping that state in JS, but if the user externally modified their clipboard, horrible things would happen. There are ways around that as well (like keeping and comparing a copy of the copied text), but the layers upon layers of hacks are unpalatable.

**Closed** 2024-03-31 06:40 UTC
Labels: editor
