### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by danielchasehooper** [witheve/Eve#195] opened 2015-08-17 22:48 UTC
After launching the run.sh, and trying to create a new table, the server crashes every time. Let me know if there additional diagnostic information I can give.

~/Downloads/Eve-master $ ./run.sh 
* Checking dependencies...
~/Downloads/Eve-master ~/Downloads/Eve-master
* Compiling Editor...
~/Downloads/Eve-master
* Opening /Users/daniel/Downloads/Eve-master/ui/waiting-room.html
~/Downloads/Eve-master ~/Downloads/Eve-master
* Updating rust if necessary...
multirust: using existing install for 'nightly-2015-08-10'
multirust: override toolchain for '/Users/daniel/Downloads/Eve-master/runtime' set to 'nightly-2015-08-10'
* Compiling server... (This takes a while)
     Running `target/debug/server`
reading saved state took 0.6763259130002552s
Connection from 127.0.0.1:51563
Connection from 127.0.0.1:51577
Send error: WebSocketError: I/O failure
thread '<main>' panicked at 'called `Result::unwrap()` on an `Err` value: Error { repr: Os { code: 22, message: "Invalid argument" } }', ../src/libcore/result.rs:732
stack backtrace:
   1:        0x10aa5c495 - sys::backtrace::write::h6ddc342d792b0e00eys
   2:        0x10aa5fb10 - panicking::on_panic::h958ebf4d6905d53emex
   3:        0x10aa4fe92 - rt::unwind::begin_unwind_inner::hbd872a23a0e4a7d76Hw
   4:        0x10aa504ec - rt::unwind::begin_unwind_fmt::h6cb11d09fc9699d1cHw
   5:        0x10aa5f4dc - rust_begin_unwind
   6:        0x10aa82d35 - panicking::panic_fmt::hbcb2030cdfd213bbTgC
   7:        0x10a86c580 - result::Result<T, E>::unwrap::h13887775847200950097
   8:        0x10a86b5c7 - server::send_event::h61b28bfb1317380bq6k
   9:        0x10a88ab48 - server::handle_event::h987e6d20378ed615Oel
  10:        0x10a88e340 - server::run::h3710c6ad17e70d89Qkl
  11:        0x10a6a5d0a - main::haf3dba23e5e43d0aiaa
  12:        0x10aa5f43d - __rust_try
  13:        0x10aa607ad - rt::lang_start::ha6eaa4ada71a9cdbh9w
  14:        0x10a6aaa7e - main
An unknown error occurred

To learn more, run the command again with --verbose.

**Comment by joshuafcole** [comment] 2015-08-17 23:01
This looks like a duplicate of #189. Please try pulling latest and let us know if that works for you. If not I'll reopen the issue so we can begin debugging.

**Closed by joshuafcole** 2015-08-17 23:01 UTC
